// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbraTsYXdFnRdDpUlZn8LgEQ21xj524rA',
    appId: '1:1064603956574:web:bd24393f63b326936e4bcf',
    messagingSenderId: '1064603956574',
    projectId: 'paytel-ab99f',
    authDomain: 'paytel-ab99f.firebaseapp.com',
    storageBucket: 'paytel-ab99f.appspot.com',
    measurementId: 'G-26B6RL8FD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSZWxj2Abxw6_ARqrl5wlVSyUK86bYP_o',
    appId: '1:1064603956574:android:973f6ff6cc564cd16e4bcf',
    messagingSenderId: '1064603956574',
    projectId: 'paytel-ab99f',
    storageBucket: 'paytel-ab99f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUDPY72lA92R5uzix8U3llxZOBWyIpktE',
    appId: '1:1064603956574:ios:dbb0536892ed3b6a6e4bcf',
    messagingSenderId: '1064603956574',
    projectId: 'paytel-ab99f',
    storageBucket: 'paytel-ab99f.appspot.com',
    iosClientId: '1064603956574-hcd3l3e3romsg6nqqgtfon3gt4ld4gog.apps.googleusercontent.com',
    iosBundleId: 'com.example.paytel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUDPY72lA92R5uzix8U3llxZOBWyIpktE',
    appId: '1:1064603956574:ios:dbb0536892ed3b6a6e4bcf',
    messagingSenderId: '1064603956574',
    projectId: 'paytel-ab99f',
    storageBucket: 'paytel-ab99f.appspot.com',
    iosClientId: '1064603956574-hcd3l3e3romsg6nqqgtfon3gt4ld4gog.apps.googleusercontent.com',
    iosBundleId: 'com.example.paytel',
  );
}
